name: Smoke Tests

on:
  repository_dispatch:
    types: [trigger-smoke-tests]

jobs:
  run-smoke-tests:
    runs-on: [self-hosted]  # Ensure runner label matches!
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Smoke Tests
        run: |
          echo "Running smoke tests on self-hosted runner"
          # Add actual test commands here
